<?php

namespace AppBundle\Repository;

/**
 * AutoModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoModeloRepository extends \Doctrine\ORM\EntityRepository
{
}
