<?php

namespace AppBundle\Repository;

/**
 * AutoCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
