<?php

namespace AppBundle\Repository;

/**
 * OficinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OficinaRepository extends \Doctrine\ORM\EntityRepository
{
}
